### ISSUE TITLE
dimension

### ISSUE THREAD

**Issue by AKFourSeven** [azz/styled-css-grid#32]
Hi I came across this package and found it really cool. Though I still have few questions about it:
- Is it possible to add width/height at the grid or grid-item level ?
- On the Cell the dimensions are in unit so it is not possible to pass in actual dimensions such as `40px` ?

**Comment by azz** [comment]
- `<Grid height="..." />` support was just added: https://github.com/azz/styled-css-grid/releases/tag/v0.11.0

- > dimensions are in unit 

  Yes, but you can use `<Cell style={{ width: '40px' }}>` for custom dimensions.

<small>(Sorry for the really late reply, the notification was accidentally dismissed.)</small>
