### ISSUE TITLE
overflow: hidden

### ISSUE THREAD

**Issue by DrShpongle** [azz/styled-css-grid#33]
Hi! Thank you for making this package. I have a question about default styles: what is the reason to keep `overflow: hidden` for the `Cell` [here](https://github.com/azz/styled-css-grid/blob/master/lib/Cell.js#L7) ? It brakes absolutely positioned elements (i.e. dropdowns) placed inside.

**Comment by azz** [comment]
This library was initially ported from a codepen css grid example that I wrote, and the display property might be a remnant of that. I'd accept a PR to remove it.

**Comment by azz** [comment]
Released in [`v0.8.2`](https://github.com/azz/styled-css-grid/releases/tag/v0.8.2), thanks! 😄
