### ISSUE TITLE
Cell middle prop does not work correctly in Firefox

### ISSUE THREAD

**Issue by jvgreenaway** [azz/styled-css-grid#45]
Here you can see `<Cell middle>` in Chome and Firefox. The layout is incorrect in Firefox.

![chrome](https://user-images.githubusercontent.com/425261/43785019-602efb7a-9a5d-11e8-8da8-898267e864f3.png)
![firefox](https://user-images.githubusercontent.com/425261/43785020-6049138e-9a5d-11e8-8d15-3a782de007ae.png)

This can be fixed by removing the `align-content: space-around` style when we apply the `middle` prop style.

Happy to create a PR if this solution is acceptable.

**Comment by azz** [comment]
Sounds good to me, provided it works in latest Edge, Firefox, Chrome and Safari.

**Comment by jvgreenaway** [comment]
Thanks for the reply! Created: https://github.com/azz/styled-css-grid/pull/47
