### ISSUE TITLE
styled-components version upgrade

### ISSUE THREAD

**Issue by smileart** [azz/styled-css-grid#46]
Currently `styled-css-grid` uses `styled-components` v2.1.1 and 

```
styled-css-grid@0.8.2" has incorrect peer dependency "styled-components@^2"
```

Meanwhile `styled-components`' current version is v3.4.2.

Basically if the comparability is not terribly broken maybe `styled-css-grid` should be updated to use a newer version of its main dependency?

Thanks! 👌

**Comment by azz** [comment]
Done!
