### ISSUE TITLE
Module not found: Can't resolve 'styled-components'

### ISSUE THREAD

**Issue by barkermn01** [azz/styled-css-grid#51]
Does not work from NPM:

```
Failed to compile.

./node_modules/styled-css-grid/dist/styled-css-grid.esm.js
Module not found: Can't resolve 'styled-components' in 'C:\GitRepos\Beaconsoft\Admin\overload-2\node_modules\styled-css-grid\dist'
```

Had to manually install styled-components from npm for it to work

**Comment by azz** [comment]
That's correct, `styled-components` is a peerDependency and as such must be installed alongside this module.

**Comment by GalGreenfield** [comment]
If it's a peerDependency for the package then why doesn't the package auto-install it?

**Comment by barkermn01** [comment]
Or better yet the guid to installing it not list that it needs to be installed, 

```
yarn add styled-css-grid
```

That should say 
```
yarn add styled-components styled-css-grid
```
