### ISSUE TITLE
Support styled-components@5 – unmet peer dependency

### ISSUE THREAD

**Issue by tupton** [azz/styled-css-grid#67]
When installing a package with `styled-css-grid` as a dependency:

> npm WARN styled-css-grid@1.2.1 requires a peer of styled-components@^2 || ^3 || ^4 but none is installed. You must install peer dependencies yourself.

In output of `npm ls styled-components`:

> npm ERR! peer dep missing: styled-components@^2 || ^3 || ^4, required by styled-css-grid@1.2.1

`styled-css-grid` appears to work fine with `styled-components@5` but the peer dependency doesn't account for it. I believe we can add this to support newer releases of `styled-components` without breaking things for current users of `styled-css-grid`.

**Comment by tupton** [comment]
This is addressed with #64

**Comment by jcrben** [comment]
forked it and published a version for my own private use which is compatible https://www.npmjs.com/package/styled-css-grid-v5 -I wouldn't rely on my package but anyone can do the same
